name: moonlight
description: Moonlight Livestream App MVP
version: 1.0.3+3

# ==== ENVIRONMENT SECTION ====
environment:
  sdk: ">=3.8.0 <4.0.0" # Matches Flutter 3.22.x
  flutter: ">=3.32.1"
# =========================

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  flutter_svg: ^2.2.2
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  get_it: ^8.2.0
  dio: ^5.3.2
  intl: ^0.20.2
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1
  image_picker: ^1.0.4
  device_info_plus: ^11.5.0
  google_sign_in: ^6.1.1 # Current stable version
  firebase_core: ^2.24.0
  firebase_auth: ^4.16.0
  http_parser: ^4.0.2
  agora_rtc_engine: ^6.5.2
  permission_handler: ^11.3.1
  record: ^6.1.1
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  rxdart: ^0.27.7
  cupertino_icons: ^1.0.6
  pusher_channels_flutter: ^2.2.1
  iconsax: ^0.0.8
  wakelock_plus: ^1.4.0
  share_plus: ^12.0.0
  skeletonizer: ^2.1.0+1
  video_player: ^2.10.0
  chewie: ^1.13.0
  video_thumbnail: ^0.5.6
  flutter_cache_manager: ^3.4.1
  shimmer: ^3.0.0
  provider: ^6.1.5+1
  mutex: ^3.1.0
  in_app_purchase: ^3.2.3
  uuid: ^4.5.2
  fluttertoast: ^9.0.0
  file_picker: ^10.3.8
  email_validator: ^3.0.0
  lottie: ^3.1.2
  connectivity_plus: ^7.0.0
  firebase_messaging: ^14.7.10
  url_launcher: ^6.3.2
  flutter_local_notifications: ^18.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6
  flutter_lints: ^6.0.0
  dartz: ^0.10.1 # For Either type
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png" # your logo path
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboard_1.jpg
    - assets/images/onboard_2.jpg
    - assets/images/onboard_3.jpg
    - assets/images/logo.png
    - assets/icons/google.svg
    - assets/icons/apple.svg
    - assets/icons/facebook.svg
    - assets/countries.json
    - assets/gifts/
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist/Urbanist-Light.ttf
          weight: 300
